import { StyleSheet } from 'react-native';
import { scale } from 'react-native-size-matters';

export const colorSchemes = {
  light: {
    background: '#F9F9F9',
    primary: '#2A2AC9',
    text: '#1A1A1A',
    card: '#FFFFFF',
    border: '#E0E0E0',
    placeholder: '#A0A0A0',
  },
  dark: {
    background: '#121212',
    primary: '#5757F7',
    text: '#FFFFFF',
    card: '#1E1E1E',
    border: '#303030',
    placeholder: '#808080',
  },
};

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 25,
  },
  contentContainer: {
    paddingBottom: scale(20),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: scale(20),
  },
  tabButton: {
    paddingHorizontal: scale(25),
    paddingVertical: scale(10),
    borderRadius: scale(20),
    marginHorizontal: scale(10),
  },
  activeTab: {
    backgroundColor: colorSchemes[theme].primary + '20',
  },
  tabText: {
    fontSize: scale(16),
    fontWeight: '500',
  },
  activeTabText: {
    color: colorSchemes[theme].primary,
    fontWeight: '600',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: scale(20),
    borderRadius: scale(15),
    padding: scale(15),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    fontSize: scale(16),
    paddingVertical: 0,
  },
  searchButton: {
    padding: scale(10),
    borderRadius: scale(12),
    marginLeft: scale(10),
  },
  sectionTitle: {
    fontSize: scale(18),
    fontWeight: '600',
    marginHorizontal: scale(20),
    marginVertical: scale(15),
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: scale(15),
    marginHorizontal: scale(20),
    marginVertical: scale(8),
    borderRadius: scale(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  locationTextContainer: {
    marginLeft: scale(15),
  },
  locationTitle: {
    fontSize: scale(16),
    fontWeight: '500',
  },
  locationAddress: {
    fontSize: scale(14),
    marginTop: scale(4),
  },
  suggestionsList: {
    paddingHorizontal: scale(20),
  },
  suggestionContainer: {
    width: scale(240),
    height: scale(160),
    borderRadius: scale(20),
    marginRight: scale(15),
    overflow: 'hidden',
  },
  suggestionImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  suggestionTitle: {
    position: 'absolute',
    bottom: scale(15),
    left: scale(15),
    color: 'white',
    fontSize: scale(16),
    fontWeight: '600',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: scale(10),
    borderTopWidth: 1,
  },
  navButton: {
    alignItems: 'center',
    padding: scale(8),
  },
  navText: {
    fontSize: scale(12),
    marginTop: scale(4),
  },
  activeNavText: {
    fontWeight: '600',
  },
  otherPages: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  servicesContainer: {
    flex: 1,
    padding: scale(20),
  },
  serviceCard: {
    flex: 1,
    margin: scale(8),
    padding: scale(15),
    borderRadius: scale(15),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  serviceIconContainer: {
    width: scale(50),
    height: scale(50),
    borderRadius: scale(12),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: scale(10),
  },
  serviceTitle: {
    fontSize: scale(16),
    fontWeight: '600',
    marginBottom: scale(5),
  },
  serviceDescription: {
    fontSize: scale(12),
    lineHeight: scale(16),
  },
  servicesList: {
    paddingBottom: scale(20),
  },
  activityContainer: {
    padding: scale(20),
  },
  activityCard: {
    padding: scale(16),
    borderRadius: scale(12),
    marginBottom: scale(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 16,
  },
  emptyContainer: {
    alignItems: 'center',
    padding: 32,
  },
  emptyButton: {
    backgroundColor: colorSchemes[theme].primary,
    borderRadius: 25,
    paddingVertical: 14,
    paddingHorizontal: 30,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colorSchemes[theme].primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#FFFFFF20',
    transform: [{ scale: 1 }],
  },
  emptyButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    marginLeft: 10,
    textAlign: 'center',
  },
  activityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(8),
  },
  activityIcon: {
    marginRight: scale(8),
  },
  activityDate: {
    fontSize: scale(12),
    flex: 1,
  },
  statusBadge: {
    paddingHorizontal: scale(8),
    paddingVertical: scale(4),
    borderRadius: scale(20),
  },
  statusText: {
    fontSize: scale(12),
    fontWeight: '500',
  },
  activityTitle: {
    fontSize: scale(16),
    fontWeight: '600',
    marginBottom: scale(4),
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  detailText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 8,
  },
  priceText: {
    fontSize: 14,
    color: '#2ecc71',
    fontWeight: '500',
    marginLeft: 8,
  },
  emptyText: {
    textAlign: 'center',
    color: '#999',
    marginTop: 32,
  },
  activityDescription: {
    fontSize: scale(14),
    lineHeight: scale(20),
    marginBottom: scale(8),
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: scale(8),
  },
  priceLabel: {
    fontSize: scale(14),
    marginRight: scale(8),
  },
  priceValue: {
    fontSize: scale(16),
    fontWeight: '600',
  },
  accountContainer: {
    padding: scale(20),
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(25),
  },
  profileImage: {
    width: scale(60),
    height: scale(60),
    borderRadius: scale(30),
    marginRight: scale(15),
    backgroundColor: '#E0E0E0',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: scale(18),
    fontWeight: '600',
    marginBottom: scale(4),
  },
  profileEmail: {
    fontSize: scale(14),
  },
  editButton: {
    padding: scale(8),
  },
  vehicleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: scale(15),
    borderRadius: scale(12),
    marginBottom: scale(10),
  },
  vehicleColor: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(8),
    marginRight: scale(15),
  },
  vehicleInfo: {
    flex: 1,
  },
  vehicleModel: {
    fontSize: scale(16),
    fontWeight: '500',
    marginBottom: scale(4),
  },
  vehiclePlate: {
    fontSize: scale(14),
    opacity: 0.8,
  },
  vehicleList: {
    marginBottom: scale(25),
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale(15),
    paddingHorizontal: scale(10),
    borderRadius: scale(12),
    marginBottom: scale(8),
  },
  optionText: {
    flex: 1,
    fontSize: scale(16),
    marginLeft: scale(15),
  },
  optionsList: {
    marginBottom: scale(30),
  },
  detailHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    paddingTop: scale(10),
    paddingBottom: scale(10),
  },
  detailBackButton: {
    marginRight: scale(10),
    padding: scale(5),
  },
  detailHeaderTitle: {
    fontSize: scale(18),
    fontWeight: '600',
  },
  detailHeroContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(30),
    borderBottomLeftRadius: scale(20),
    borderBottomRightRadius: scale(20),
    marginBottom: scale(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailHeroIcon: {
    marginBottom: scale(10),
  },
  detailHeroTitle: {
    fontSize: scale(22),
    fontWeight: 'bold',
    textAlign: 'center',
    paddingHorizontal: scale(20),
  },
  detailContentContainer: {
    paddingHorizontal: scale(20),
    paddingBottom: scale(20),
  },
  detailSectionTitle: {
    fontSize: scale(16),
    fontWeight: '600',
    marginBottom: scale(6),
  },
  detailDescription: {
    fontSize: scale(14),
    lineHeight: scale(20),
  },
  detailActionButton: {
    marginVertical: scale(20),
    paddingVertical: scale(14),
    borderRadius: scale(10),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailActionButtonText: {
    fontSize: scale(16),
    fontWeight: '600',
  },
  mapContainer: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  searchBox: {
    position: 'absolute',
    top: 20,
    width: '90%',
    alignSelf: 'center',
    backgroundColor: colorSchemes[theme].card,
    borderRadius: 8,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  suggestionsDropdown: {
    position: 'absolute',
    left: 0,
    right: 0,
    borderRadius: 8,
    elevation: 5,
    maxHeight: 200,
    zIndex: 1000,
    marginTop: 10,
    padding: 0,
    backgroundColor: colorSchemes[theme].card,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  suggestionTextContainer: {
    marginLeft: 10,
    flex: 1,
  },
  suggestionTitleDropdown: {
    fontSize: 16,
  },
  suggestionSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    justifyContent: 'center'
  },
  noResults: {
    padding: 15,
    textAlign: 'center',
    color: '#888'
  },
  historyItemContainer: {
    overflow: 'hidden',
    marginHorizontal: scale(15),
    marginVertical: scale(5),
    borderRadius: scale(8),
  },
  deleteContainer: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ff574d',
    zIndex: 0,
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: scale(15),
    borderRadius: scale(8),
    zIndex: 1,
  },
  historyTextContainer: {
    marginLeft: scale(15),
    flex: 1,
  },
  historyTitle: {
    fontSize: scale(16),
  },
  navigationButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
  },
}); 